### ISSUE TITLE
only move files of a source folder without deleting the folder

### ISSUE THREAD

**Issue by nise** [andrewrk/node-mv#13]
I tried to move the files that are inside a folder without deleting the folder itself. I wanted to have an upload folder but mv always deletes the folder. 
If the source path is defined as "path/to/source/*" nothing will be moved. 

I would expect a behaviour like the unix command 'mv'. 

Could you document how to obtain this?

**Comment by andrewrk** [comment]
`*` is bash syntax. The `mv` binary never sees the asterisk. This module moves only a single file or a single directory. If you want to move multiple files you have to iterate over them and move them independently.

**Comment by nise** [comment]
Thank you for the answer. I am woundering if your suggested work around is not too inefficient. Anyway, I am fine with the great help you provide me with mv.

**Comment by andrewrk** [comment]
The workaround that I suggested is the same thing that happens when you do `mv foo/* dest/` with the posix command. So if it's too inefficient, then so is linux.
