### ISSUE TITLE
Typo in usage docs

### ISSUE THREAD

**Issue by bgSosh** [andrewrk/node-mv#14]
var mv = require('mv');

Should be 

var mv = require('node-mv');

**Comment by jprichardson** [comment]
This is incorrect. You're confusing https://www.npmjs.com/package/node-mv
for https://www.npmjs.com/package/mv

On Tue, Feb 10, 2015 at 7:41 AM, bgSosh <notifications@github.com> wrote:

> var mv = require('mv');
>
> Should be
>
> var mv = require('node-mv');
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/andrewrk/node-mv/issues/14>.
>



-- 
Simple & Secure Bitcoin Wallet: https://www.coinbolt.com
Bitcoin / JavaScript: http://cryptocoinjs.com
Follow me on Twitter: http://twitter.com/jprichardson

**Comment by bgSosh** [comment]
Doh - sorry!

**Comment by jprichardson** [comment]
No worries :)

On Tue, Feb 10, 2015 at 8:05 AM, bgSosh <notifications@github.com> wrote:

> Doh - sorry!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/andrewrk/node-mv/issues/14#issuecomment-73703767>.
>



-- 
Simple & Secure Bitcoin Wallet: <https://www.coinbolt.com>
https://www.coinbolt.com
Bitcoin / JavaScript: <http://cryptocoinjs.com> http://cryptocoinjs.com
Follow JP Richardson: <https://twitter.com/jprichardson>
https://twitter.com/jprichardson
