### ISSUE TITLE
Upgrading rimraf broke moves of filenames containing [ and *

### ISSUE THREAD

**Issue by cscott** [andrewrk/node-mv#16]
The new version of `rimraf` expands globs by default.  This breaks node-mv if you try to move files containing glob characters.

To fix this, you should explicitly pass `{ disableGlob: true }` as the second option to `rimraf` whenever it is used.

**Comment by andrewrk** [comment]
Fuck, what a disaster.

**Comment by andrewrk** [comment]
They changed that in a minor version upgrade?!

**Comment by andrewrk** [comment]
Fixed by aed9a5c688a7f7ee760
